### ISSUE TITLE
Observable.call(this)

### ISSUE THREAD

**Issue by jwarnox** [pakastin/frzr#18]
Hi, following your blog posts and very excited about the simplicity of FRZR (great name by the way) I have a question? in view.js in the constructor function is the first line:

Observable.call(this);

which will create:

this.listeners = {};

on the View instance, so how come the prototype methods of on, off, trigger are added to the new View without instantiating Observable with new, I recreated the code and got .on is not a function etc…

regards,
Jamie

**Comment by pakastin** [comment]
Hi!

This line inherits `View` from `Observable`:
https://github.com/pakastin/frzr/blob/master/src/view.js#L39

The `inherits` function can be found from here:
https://github.com/pakastin/frzr/blob/master/src/utils.js#L28

I checked with codepen and methods seem to work just fine:
http://codepen.io/pakastin/pen/NxpmWK

The point is to instantiate `View` with `new View(options, data)`, otherwise use the `view(options, data)` notation (it will add `new` keyword for you). Also using `var CustomView = View.extend(options)` will require you to use `new CustomView(data)` and `var customView = view.extend(options)` doesn't.. Makes sense? :)

They're defined here:
https://github.com/pakastin/frzr/blob/master/src/view.js#L238

**Comment by pakastin** [comment]
There's also `ViewList` (needs `new` keyword) and `viewList` (doesn't need).
Think `View` and `ViewList` as classes and `view` and `viewList` as factories.

Maybe I should make a check to `View` that the user is using `key`..

**Comment by jwarnox** [comment]
Hi Juha,

Thank you for the in-depth response, I missed the Inherits utility function, makes perfect sense now, I really like where you are going with the simplicity of FRZR, your API is a very transparent thin layer on the Dom API, great work.

Do you have any ideas for reusable components? say for example a counter component that embeds say two swatch components that display count and clicks, where you can easily reuse and add these component group instances to the Dom

Also when do you think part 2 in your blog series will be published?

regards,
Jamie

**Comment by pakastin** [comment]
Here is an example of making components:
http://codepen.io/pakastin/pen/MKpMyM

Btw. I just added server-side rendering as a beta (v. 0.8.1). When you're using FRZR from Node.js, you'll get this new `View.render()` method, which will return HTML. You also have `frzr.server` -variable, which will return `true` when running on the server.

Have fun! ;)

**Comment by pakastin** [comment]
Btw. If you need more complex components (or just like more traditional approach), you can create your own custom Views manually:

```
function CustomView (data) {
  ...
  frzr.View.call(options, data);
  ...
}
frzr.inherits(CustomView, frzr.View);
frzr.define(CustomView.prototype, {
  customMethod: function () {
    ...
  }
});
```

Or with ES6:
```
class CustomView extends frzr.View {
  constructor (data) {
    super(options, data);
    ...
  }
}
```

**Comment by pakastin** [comment]
Here's another example of "nested" components:
http://pakastin.fi/frzr-test/

Source:
http://pakastin.fi/frzr-test/main.js (view logic)
http://pakastin.fi/frzr-test/api.js (data logic inside web worker)

I will probably publish that example in github in some point. I was just testing a redux-like logic with web workers. Turned out it works quite fast and smooth, even on mobile ;)

**Comment by pakastin** [comment]
Here's similar example in Github:
https://github.com/pakastin/worker-example
