### ISSUE TITLE
Better documentation of the frzr.List

### ISSUE THREAD

**Issue by hville** [pakastin/frzr#25]
The documentation, example and code for the `frzr.List` function are all different. It would really help if we could distinguish what is part of the standard internal model and what are just custom methods and properties.

### 1. In the documentation (`readme.md`)
```
var Component = () => {el, update}  // no arguments ever shown
var myList = new List(Component, key, initData)  //missing the 4th parameter
```
  - Component never has any parameters
  - List takes 3.

### 2. In the codepen examples
```
var list = new List(View, key, initData, true)  
```
  - The Component constructor is called View
  - List takes 4 parameters

### 3. in the source code
```
var myList = new List(View, key, initData, skipRender)
view = new View(initData, item, i)
```
  - The Component constructor is called View and takes 3 arguments
  - List takes 4 parameters

### Questions and Suggestions: ###
* present a complete signature for a component object. I am guessing it is `{el: DomElement, update: (data)=>void}`
* present a complete signature for a Component constructor. I am not too sure. Is it `(collection, item, index)=>component`? Possibly rename it to View to match the example and code.
* Also, List overrides all parent children so the following would fail: `var myEl = el('div', Component(), list(Component))'` (the first child is deleted by the second child). Is this a case to be documented or a bug to be fixed?
* What if the data is a matrix and the key is the index? `list(Component, null, matrix)`?

**Comment by pakastin** [comment]
Hi!

First of all, thank you so much for the contribution. 👍

The current documentation / examples are lacking, you're so right. I'm creating new websites at the moment (sneak peek: http://pakastin.fi/frzr, source: https://github.com/pakastin/frzr/tree/new-website). I will write a better documentation there.

Answers to your questions:
- component (or View) only needs an `el` property, even `update` is not mandatory
  - only `List` is actually using the `update` method [here](https://github.com/pakastin/frzr/blob/master/src/list.js#L54) and [here](https://github.com/pakastin/frzr/blob/master/src/list.js#L90) and it checks if it's there or not

- component's constructor signature depends on where you're using it (it's just a plain old Javascript function / class)
  - with `List` it's `(initData, item, index)`, called [here](https://github.com/pakastin/frzr/blob/master/src/list.js#L46) and [here](https://github.com/pakastin/frzr/blob/master/src/list.js#L84). If you need access to the `List` from a component, you can provide it with `initData`. There's also a "secret" `parent` -property, which is added [here](https://github.com/pakastin/frzr/blob/master/src/mount.js#L42).

- `setChildren`, which `List` uses [here](https://github.com/pakastin/frzr/blob/master/src/list.js#L95) overrides all the current children, that's correct. You can disable that by setting the fourth `skipRender` parameter to `true` and introducing you're own update method, like done in my animated list example you're referring to.
  - if you give a better example of what you're doing, I can help you out with that.. 😊

  - remember that FRZR is not a virtual dom library, so keeping old and new in sync and in place would need placeholders etc. – I like to keep things really pure simple, so that's why it's like it is

- if `key` is set to null, `List` uses `index`, so you're example should work alright.

Thank you for the feedback, it's really valuable to learn how people understand (or don't 😀) the library!

**Comment by pakastin** [comment]
If you have any further questions, I'm happy to answer.

**Comment by pakastin** [comment]
I actually updated the current documentation a bit.. Hope it's better for now!

**Comment by hville** [comment]
Great. Thanks for such a prompt reply. I've been playing around with FRZR most of the day and it is very different and refreshing to come across simple new ideas like this. I really like it.

No major issues, I got everything to work but had to look at the source code all along to really get anywhere. My point was about saving some issues for the next user.

* `component.update`: For all but the most trivial examples, nested components are the norm so I think it is good to standardize an update method even if it is optional so that users can eventual have shareable and compatible components.

* I'm a little puzzled why the individual View inside a List takes `(initDataArray, newDataItem, index)`. Wouldn't it be more intuitive if it followed the more standard `(item, index, value)` order so that the same constructor can be used in Array methods? No big deal but it does causes additional initial bugs because it is unusual and I keep going back to the source code to remember how it is done. Unless of course I am missing the bigger picture...

Thanks again.

**Comment by pakastin** [comment]
Yeah I totally realize that. The reason the documentation is so lacking is, because FRZR has changed a lot (mainly simplified) and just now it's starting to be like I want it to be. If you compare the [version 0.2.2](https://cdnjs.cloudflare.com/ajax/libs/frzr/0.2.2/frzr.js) (the first unminified version in cdnjs 😊) to the latest version (https://frzr.js.org/frzr.js), you'll probably see what I mean. It even was forked to two separate projects `@pakastin/f` and `rzr` (virtual dom version), and merged back.

The current version will become 1.0 – I will release it when the new websites are ready.

About those questions:

- `update` method is of course preferrable

- `initData` is sometimes quite useful, if you need to have references upwards the component tree, `item` is really rarely needed (because `update` method handles the updates, even the init one) and `index` is only for really custom cases..

  - In 99 % of the use cases you don't need constructor parameters at all, try to switch the mindset and use the `update` method instead for the initialization as well.. Structure your component so that you only define "static" things in the constructor and the dynamic stuff in the `update` function.

    For example:
    ```js
    import { el, text, mount, List } from 'frzr';

    class Hello {
      constructor () {
        this.el = el('h1', 
          this.greeting = text(''),
          ' ',
          this.target = text(''),
          '!'
        );
      }
      update (data) {
        this.greeting.textContent = data[0];
        this.target.textContent = data[1];
      }
    } 

    const list = new List(Hello);

    list.update([
      ['Hello', 'world'],
      ['Hola', 'mundo'],
      ['你好', '世界']
    ]);

    mount(document.body, list);
    ```
    https://jsfiddle.net/9ob01n7a/

**Comment by pakastin** [comment]
Here's also a good example of using components:
https://github.com/pakastin/frzr-calendar/blob/master/js/calendar.js
http://pakastin.github.io/frzr-calendar/

**Comment by pakastin** [comment]
Here's more dynamic example: 
https://github.com/pakastin/frzr/blob/new-website/website/js/content.js

..and one with rich DOM manipulation:
https://github.com/pakastin/frzr/blob/new-website/website/js/overlay-topbar.js

**Comment by hville** [comment]
Got it. Sweet.
